### ISSUE TITLE
Investigación Framework CSS

### ISSUE THREAD

**Issue by rrodriguezgon** [MirionsDevTeam/event-planning-front#1]
Tailwind css -> https://tailwindcss.com/
 
Librerías de Tailwind:
Flowbite -> https://flowbite.com/
DaisyUI -> https://daisyui.com/

Por último, un post de referencia sobre librerías de componentes creadas en base a Tailwind:
https://www.reddit.com/r/nextjs/comments/1715625/11_best_tailwind_css_component_libraries_in_2023/

**Comment by rrodriguezgon** [comment]
Opción => https://mui.com/material-ui/getting-started/
Investigación => Tailwind

**Comment by rrodriguezgon** [comment]
- [x] Marcamos como objetivo crear un ejemplo sencillo para mostrar el funcionamiento de estas librerias.
- [ ] Crear clases base para elementos comunes, iniciando con la pantalla de login.

**Comment by JoseLuisDiazAlonso** [comment]
He creado un ejemplo sencillo de uso de tailwind. Para ello he creado un ejemplo de pantalla de login con dos input....uno de nombre de usuario, otro con contraseña y le he añadido algunos estilos para que se pueda ver como se trabaja con este tipo de librería.

**Comment by Saragc5** [comment]
He creado un mini proyecto para crear la pantalla Home en base al diseño inicial  en blanco que hay aquí en las tarjetas para ir probando Tailwind y las librerías, uno de los componentes lo he creado con Tailwind y una copia + su archivo CSS.

Captura de pantalla Home:
![Image](https://github.com/MirionsDevTeam/event-planning-front/assets/105001891/262c97f2-5011-4042-8c82-ff282c050d4e)
Captura pantalla mismo componente con clases Tailwind y con clases CSS:
![Image](https://github.com/MirionsDevTeam/event-planning-front/assets/105001891/2df23a8b-35c7-4559-84a6-480ea9389a61)
Captura de componente que lleva archivo CSS:
![Image](https://github.com/MirionsDevTeam/event-planning-front/assets/105001891/b2ec2f11-f7a9-4c54-b86b-94b1a21f4109)

He creado componentes también usando la librería Daisy y personalizando el componente, por ejemplo el menú de abajo, usando el componente Menu de la librería.

Me queda conseguir que si creo una clase personalizada, me funcione. Lo he hecho anteriormente en otro proyecto pero en este no se me aplica. Sigo con esto para terminarlo antes del jueves.

**Comment by Saragc5** [comment]
Añado enlace al repositorio: https://github.com/Saragc5/mirions-home
