### ISSUE TITLE
Crear Pantalla login

### ISSUE THREAD

**Issue by rrodriguezgon** [MirionsDevTeam/event-planning-front#6]
Como equipo de Frontend necesitamos crear la pantalla para acceder a la aplicación con los siguientes inputs y botones:

- Logotipo => Imagen
- Usuario => input
- Password => input
- Login => Botón
- "Recuperar contraseña" => Link
-  "No account? Register" => Link 

Opcional?: Creación tanto pantalla como testing.

Para poder acceder a la aplicación, registrarse o recuperar la contraseña "olvidada".

![Image](https://github.com/MirionsDevTeam/MirionsProject/assets/65360106/786542d6-6cbd-468d-9584-053e75003422)

**Comment by rrodriguezgon** [comment]
Programas para diseño web:

El rey por antonomasia -> https://www.figma.com/
La alternativa Open source ->  https://penpot.app/

**Comment by rrodriguezgon** [comment]
- Se ha elegido penpot como opción para los diseños.
- Se está iniciando la coordinación para los mismos.
- En breve tendremos algo unificado para Login y SIgnUp.
- Pendiente adjuntar url similar para acceder a los diseños colaborativos.

**Comment by paulacozycode** [comment]
https://design.penpot.app/#/view/93d0ad32-dfe5-8194-8003-ff4cc9b6bc50?page-id=93d0ad32-dfe5-8194-8003-ff4cc9b6bc51&section=interactions&index=0&share-id=43442e9d-d45f-8169-8004-00c5e594b3f4

El enlace lleva directamente al prototipo.

1. Usamos el color de Miriam porque somos Mirions(?), no hay otra explicación lógica. 
2. Este prototipo tiene un flujo así: Enlace en Login the lleva a Sign Up, enlace en Sign Up the lleva a Login. El resto de los botones no funciona porque hay crear las siguientes vistas.
3. Es una reiteración de la imagen de referencia, tengo también la posible vista a cómo se vería en web, pero no la he acomodado para mostrar. (pero si quieren: https://design.penpot.app/#/view/93d0ad32-dfe5-8194-8003-ff4cc9b6bc50?page-id=cbe8351f-8906-80cb-8004-00703f0ec728&section=interactions&index=0&share-id=93d0ad32-dfe5-8194-8004-00c8cd044e0b)
4. El ojo en la parte de contraseña lo dibujé a mano, perdonen, se ve feo y a la vez no tanto.
5. Falta invitarlos al espacio de trabajo que creamos en penpot. 
6. Es básico, pero no tenemos nombre, ni logo, ni colores, pero sirve e ilustra visualmente como se pudiera ver el login y el signup y el flujo entre ambas.

**Comment by rrodriguezgon** [comment]
Crear repositorio de "adjuntos" "recursos" para almacenar toda la información últil indicada en las tarjetas de tareas.

**Comment by rrodriguezgon** [comment]
Creado repositorio para almacenar utilidades, enlaces y demás.  

Link Repositorio: https://github.com/MirionsDevTeam/event-planning-utils
