### ISSUE TITLE
Crear clases bases de TailwindCSS

### ISSUE THREAD

**Issue by rrodriguezgon** [MirionsDevTeam/event-planning-front#9]

**Comment by Saragc5** [comment]
He creado un par de clases personalizadas en Tailwind como prueba del diseño que hice la semana pasada y he empezado a escribir el código de la pagina login para implementar las clases base de los inputs y botón, en base al diseño de Paula de penpot.
Las clases de los inputs están, tengo que terminar el botón y colocarlo todo en la pagina para mostrarlo.

**Comment by Saragc5** [comment]
La clase personalizada para los input del formulario está terminada.
Estoy con la clase para los botones morados.

**Comment by JoseLuisDiazAlonso** [comment]
Basándome en el diseño de Paula (Aunque a ella la ha quedado más bonito). He creado las clases para los inputs y los botones.

**Comment by Saragc5** [comment]
He creado un archivo separado para las custom class css en Styles/custom.css.
He subido (al repo de prueba que hice la última vez) el componente botón, login y register sin funcionalidad solo diseño con las clases base personalizadas. Éstas luego se pueden utilizar y añadir sobre ellas más clases Tailwind ya en el html si se desea cambiar o añadir algo.

**Comment by Saragc5** [comment]
Esta semana me pongo con la pantalla Home siguiendo el diseño que está haciendo Paula

**Comment by rrodriguezgon** [comment]
@Saragc5 si quieres puedes trasladar lo que tengas listo al repositorio nuevo creado en alguna carpeta o así como mas cómodo sea.

https://github.com/MirionsDevTeam/event-planning-utils

**Comment by Saragc5** [comment]
Ok, esta noche lo miro
